app = "tweetx-backend"
primary_region = "sin"  # Singapore region, you can change this to a region closer to your users

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  API_V1_STR = "/api/v1"
  PROJECT_NAME = "TweetX"
  DEBUG = "False"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512 